---
- name: Check whether exa is intalled
  ansible.builtin.shell: exa
  register: exa_installed
  changed_when: false
  ignore_errors: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install Rust
  ansible.builtin.shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: exa_installed is failed

- name: Install required packages
  ansible.builtin.package:
    name: '@Development Tools'
    state: present
  when: exa_installed is failed

- name: Install exa with cargo
  ansible.builtin.shell: |
    /bin/bash -lc "cargo install --no-default-features exa"
  when: exa_installed is failed

- name: Copy exa executable file to '/usr/local/bin'
  ansible.builtin.copy:
    src: /root/.cargo/bin/exa
    dest: /usr/local/bin/exa
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  when: exa_installed is failed

- name: Delete exa executable file
  ansible.builtin.file:
    path: /root/.cargo/bin/exa
    state: absent
  when: exa_installed is failed
